version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: blog-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"

  backend:
    build: ../blog-backend
    container_name: blog-api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db/blogdb
    ports:
      - "8000:8000"

  frontend:
    build: ../blog-frontend
    container_name: blog-ui
    depends_on:
      - backend
    ports:
      - "3000:3000"
